# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.cache/wt [current_project]
set_property parent.project_path F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/new/arp/arp.v
  F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/new/arp/arp_rx.v
  F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/new/arp/arp_tx.v
  F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/new/ov7725/cmos_capture_data.v
  F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/new/arp/crc32_d8.v
  F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/new/eth_ctrl.v
  F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/new/eth_top.v
  F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/new/gmii_to_rgmii/gmii_to_rgmii.v
  F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/new/ov7725/i2c_dri.v
  F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/new/ov7725/i2c_ov7725_rgb565_cfg.v
  F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/new/img_data_pkt.v
  F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/new/gmii_to_rgmii/rgmii_rx.v
  F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/new/gmii_to_rgmii/rgmii_tx.v
  F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/new/start_transfer_ctrl.v
  F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/new/udp/udp.v
  F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/new/udp/udp_rx.v
  F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/new/udp/udp_tx.v
  F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/new/ov7725_udp_pc.v
}
read_ip -quiet F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all f:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_ooc.xdc]

read_ip -quiet F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/ip/async_fifo_1024x32b_1/async_fifo_1024x32b.xci
set_property used_in_implementation false [get_files -all f:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/ip/async_fifo_1024x32b_1/async_fifo_1024x32b.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/ip/async_fifo_1024x32b_1/async_fifo_1024x32b_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/ip/async_fifo_1024x32b_1/async_fifo_1024x32b_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/constrs_1/new/eth_udp_loop.xdc
set_property used_in_implementation false [get_files F:/ZYNQ/FPGA_Design/ov7725_udp_pc/ov7725_udp_pc.srcs/constrs_1/new/eth_udp_loop.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ov7725_udp_pc -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ov7725_udp_pc.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file ov7725_udp_pc_utilization_synth.rpt -pb ov7725_udp_pc_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
