# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/IC/1_Work/DIP/OV7725_DIP/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/ip/async_fifo_1024x32b_1/async_fifo_1024x32b.xci
# IP: The module: 'async_fifo_1024x32b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/IC/1_Work/DIP/OV7725_DIP/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/ip/async_fifo_1024x32b_1/async_fifo_1024x32b.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_1024x32b'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/IC/1_Work/DIP/OV7725_DIP/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/ip/async_fifo_1024x32b_1/async_fifo_1024x32b_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_1024x32b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/IC/1_Work/DIP/OV7725_DIP/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/ip/async_fifo_1024x32b_1/async_fifo_1024x32b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_1024x32b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/IC/1_Work/DIP/OV7725_DIP/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/ip/async_fifo_1024x32b_1/async_fifo_1024x32b.xci
# IP: The module: 'async_fifo_1024x32b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/IC/1_Work/DIP/OV7725_DIP/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/ip/async_fifo_1024x32b_1/async_fifo_1024x32b.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_1024x32b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/IC/1_Work/DIP/OV7725_DIP/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/ip/async_fifo_1024x32b_1/async_fifo_1024x32b_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_1024x32b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/IC/1_Work/DIP/OV7725_DIP/ov7725_udp_pc/ov7725_udp_pc.srcs/sources_1/ip/async_fifo_1024x32b_1/async_fifo_1024x32b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_1024x32b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
